vim.opt.shiftwidth     = 4
vim.opt.tabstop        = 4
vim.opt.number         = true
vim.opt.relativenumber = true
vim.opt.clipboard      = "unnamedplus"
vim.o.termguicolors    = true
vim.opt.breakindent    = true
vim.opt.autoindent     = true
vim.opt.smartindent    = true
vim.opt.completeopt    = { "menu", "menuone", "noselect" }
