#!/bin/bash

read -s -p "Enter gocryptfs password: " password
echo

if [ -z "$password" ]; then
  echo "No password entered. Exiting."
  exit 1
fi

echo "$password" | gocryptfs -nosyslog ~/Journal/cipher ~/Journal/Journal

# Launch Obsidian in background
obsidian ~/Journal/ &

# Get Obsidian PID by process name (works if only one instance)
echo "Waiting for Obsidian to close..."
while pgrep -x "obsidian" >/dev/null; do
  sleep 2
done

fusermount -u ~/Journal/Journal
echo "Encrypted folder unmounted."
