#!/bin/bash

# Switch to the postgres user
sudo su - postgres <<EOF
# Start the PostgreSQL server
/usr/local/pgsql/bin/pg_ctl -D /usr/local/pgsql/data -l logfile start
EOF

# Confirm that the script ran
echo "PostgreSQL server started."
